### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mindiell** [numerique-gouv/django-dsfr#117]
Pourquoi ne pas positionner la documentation (actuellement example_app si j'ai bien compris) dans le répertoire doc qui sert à ça d'habitude ?

**Comment by Ash-Crow** [comment]
Parce que c'est à la base une application d'exemple qui a évolué pour permettre de générer la documentation (qui elle-même est sur Github Pages : https://numerique-gouv.github.io/django-dsfr/ )
