### ISSUE TITLE
Problème d'affichage du label des cases à cocher

### ISSUE THREAD

**Issue by HaRicoVert** [numerique-gouv/django-dsfr#124]
Concernant, le tag `{% dsfr_form_field %}`, lorsqu'une case à cocher est présentée seule, elle est affichée avant le libellé, conformément au DSFR. Cependant, dans ce contexte, les ":" (deux points) qui suivent habituellement le libellé sont quand même affichés après le libellé, ce qui peut sembler incohérent. Pour rendre l'interface plus logique et cohérente, il serait préférable de ne pas afficher les ":" lorsque le type d'input est une case à cocher. Ainsi, cela correspondrait mieux à l'affichage de la case à cocher avant le libellé.

Ce qui est affiché actuellement :
![numerique-gouv github io_django-dsfr_form_example_ (1)](https://github.com/numerique-gouv/django-dsfr/assets/101187637/6b67df32-cee5-4bc7-aa5d-51b0426bed5b)
```html
<div class="fr-checkbox-group">
    <input type="checkbox" name="sample_boolean" id="id_sample_boolean" />
    <label for="id_sample_boolean" class="fr-label">
        <label for="id_sample_boolean">Cochez la case&nbsp;:</label>
    </label>
</div>
```

Ce qui devrait être idéalement affiché :
![numerique-gouv github io_django-dsfr_form_example_ (2)](https://github.com/numerique-gouv/django-dsfr/assets/101187637/4313b9f9-1f59-400e-b94d-b1ee386ed1eb)
```html
<div class="fr-checkbox-group">
    <input type="checkbox" name="sample_boolean" id="id_sample_boolean" />
    <label for="id_sample_boolean" class="fr-label">
        <label for="id_sample_boolean">Cochez la case</label>
    </label>
</div>
```

**Comment by Ash-Crow** [comment]
Merci pour le signalement !
