### ISSUE TITLE
Ajouter les boutons radio riches dans les formulaires

### ISSUE THREAD

**Issue by Ash-Crow** [numerique-gouv/django-dsfr#126]
Les [boutons radio riches](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bouton-radio-riche) sont un champ avancé qui n'a pas d'équivalent direct dans Django. Il faudrait cependant pouvoir les gérer dans Django-DSFR autrement qu'en construisant le formulaire à la main.

- [Documentation des boutons radio dans Django](https://docs.djangoproject.com/en/3.2/ref/forms/widgets/#radioselect)

**Comment by christophehenry** [comment]
Sur [betagouv/Aidants_Connect](https://github.com/betagouv/Aidants_Connect), j'ai écrit un widget pour faire ça. Malheureusement, [j'ai dû écrire du code spécifique](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_common/constants.py#L71-L82) pour pouvoir ajouter un pictogramme et une image ([exemple d'utilisation](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_common/constants.py#L71-L82)). Je suis pas très satisfait de cette solution mais je vois pas comment faire mieux…

**Comment by christophehenry** [comment]
Awesome ! Ça te va si je travaille à une version verticale ? Et une version checknox ? On en a besoin dans Aidants Connect. J'ai ouvert un TK pour l'avoir dans le DSFR, mais ça n'y est pas encore. Du coup, à toi de me dire si tu veux attendre le DSFR et que tu préfères qu'on le mettre en local.
