### ISSUE TITLE
Migrer code normatif depuis example_app à DSFR (Architecture)

### ISSUE THREAD

**Issue by chris2fr** [numerique-gouv/django-dsfr#144]
Il y a un défaut d’architecturalement que j'estime important. Le code pour l'exécution normale de l'application se trouve trop dans le dossier example_app. Ceci pose un problème important d'unifomalité et d'automatismes de transpositions / traductions (traductions au sens propre). 

Faisons en sorte que DSFR (devrait-il être django_dsfr au fait, y compris dans templates et static ?) reprennent le code de example_app qui n'a pas besoin d'être dans example APP. Je pense par exemple à Search.

**Comment by Ash-Crow** [comment]
Bonjour,

Non, c'est normal que cela soit comme ça : la recherche via une librairie Javascript est une implémentation spécifique au site d'exemple (qui est un export statique)

Un site Django normal fonctionnera différemment (et l'implémentation va dépendre des modèles utilisés)

**Comment by Ash-Crow** [comment]
Pour ce qui est des phrases à traduire, je ne suis pas trop sûr de la meilleure façon de faire, et je me demande si tout simplement faire une page reprenant tous les snippets de https://www.systeme-de-design.gouv.fr/ qui ne sont pas utilisés directement dans la librairie ne réglerait pas le problème (après fondamentalement, l'idéal serait que le SIG fournisse lui-même le DSFR internationalisé avec ses traductions dans les langues de l'Union ainsi que les langues régionales et minoritaires de France.)

**Comment by Ash-Crow** [comment]
> (devrait-il être django_dsfr au fait, y compris dans templates et static ?)

Pour cette partie : pas forcément, c'est assez commun de faire comme ça pour les paquets django (par exemple https://github.com/zostera/django-bootstrap4/ a aussi l'app sous "bootstrap4" sans le "django-" devant), et surtout ça ne me paraît pas une bonne idée de changer à posteriori, ça risque de casser des trucs sur des projets qui utilisent le paquet et ont personnalisé les templates.
