### ISSUE TITLE
Déprecier {% dsfr_form %} pour Django 4.0+

### ISSUE THREAD

**Issue by christophehenry** [numerique-gouv/django-dsfr#152]
Django 4.0 [a introduit l'API Form rendering](https://docs.djangoproject.com/en/dev/ref/forms/api/#default-rendering) qui rend `{% dsfr_form %}` obselète. Je propose de modifier `{% dsfr_form %}` pour lever une notice de dépreciation à partir de Django 4.0+ et supprimer le support dans la prochaine majeure et supprimer totalement la balise quand il sera décidé de laisser tomber le support de Django<4.0.

**Comment by Ash-Crow** [comment]
Bonjour, pas sûr de comprendre, par quoi serait-il remplacé ?

**Comment by Ash-Crow** [comment]
Hello @christophehenry  ! Est-ce que tu peux s'il te plaît regarder la PR et me dire si c'est ce que tu avais en tête ?

**Comment by christophehenry** [comment]
Oui, c'est bien ça que j'avais en tête.
