### ISSUE TITLE
Problème avec dsfr_alert

### ISSUE THREAD

**Issue by B-Alica** [numerique-gouv/django-dsfr#77]
Bonjour,

Je rencontre un problème au niveau des dsfr_alert. Après avoir bien fouillé avec des collègues, nous pensons (sans être sûrs) que le problème vient d'une boucle javascript quelque part qui aurait une erreur.

**Le problème :** lorsque je mets un {% dsfr_alert foo %} dans un template, l'alerte ne s'affiche pas. Pourtant elle existe bien, elle est présente dans le code html de la page, mais il manque à la div du message la classe "fr-collapse--expanded" ainsi que "style="--collapse-max-height: none; --collapse: -44px;". En rajoutant à la main dans l'inspecteur cette classe et ce style dans la div, le message s'affiche bien.
Mon html : 
![image](https://github.com/numerique-gouv/django-dsfr/assets/98895870/a9bd4a75-64f2-4ac8-b29a-b77bcd871d6d)

Le rendu sur la page : rien

Ce que je vois dans l'inspecteur : 
![image](https://github.com/numerique-gouv/django-dsfr/assets/98895870/ba621f10-d85a-4388-917a-da5d5f10f67e)
(l'alerte existe mais elle ne s'affiche pas)

En rajoutant à la main ce qu'il faut : 
![image](https://github.com/numerique-gouv/django-dsfr/assets/98895870/7da02880-938d-48b7-ad7a-964eb0b1e741)

Le rendu sur la page : 
![image](https://github.com/numerique-gouv/django-dsfr/assets/98895870/3a8c11e4-7f3c-4383-abee-c9bef8372547)
(l'alerte s'affiche désormais).

Plus étrange encore : Si je mets DEUX FOIS mon alerte, comme ceci : 
![image](https://github.com/numerique-gouv/django-dsfr/assets/98895870/c4771de8-d076-440c-8c5f-8889b793d510)
(Deux fois exactement la même)

Le rendu : 
![image](https://github.com/numerique-gouv/django-dsfr/assets/98895870/fa269d46-87e7-47ce-bceb-fd4552702dea)
(L'alerte n'apparait qu'une seule fois)

Ce qu'on voit sur l'inspecteur : 
![image](https://github.com/numerique-gouv/django-dsfr/assets/98895870/3a8129d1-bbc0-4b3e-be7c-ed3dc5aa7e82)

Les deux alertes existent dans le code, mais seule la première a reçu la classe fr-collapse--expanded et le style qui convient, pas la deuxième.

C'est ce qui nous fait penser qu'il doit y avoir une boucle quelque part qui ajoute la classe fr-collapse--expanded à toutes les div de message, mais avec une erreur de type commencer à 1 plutôt que 0.

Savez-vous ce qui peut causer ça ? Rencontrez-vous le même problème ?

A savoir que j'utilisais une ancienne version de django-dsfr (0.11.1) et mon code marchait sans problème en ne mettant qu'une seule fois {% dsfr_alert message.message|to_dict %}. C'est depuis que j'ai fait la mise à jour vers django-dsfr 0.16.2 que j'ai ce bug.
J'espère que ma description du problème est claire, ce n'est pas facile à expliquer.

Je vous remercie,

Cordialement.

**Comment by Ash-Crow** [comment]
J'ai fait une correction dans #81 qui corrige le problème qui apparaissait aussi dans la doc. Par contre je ne sais pas ce qui causait le comportement incohérent quand l'alerte était présente deux fois : est-ce que ça corrige le problème chez vous aussi ?

**Comment by B-Alica** [comment]
Bonjour,
Ca a l'air de fonctionner chez moi aussi.
