### ISSUE TITLE
Créer un DsfrModelForm et déprécier la combinaison de ModelForm et DsfrBaseForm

### ISSUE THREAD

**Issue by Ash-Crow** [numerique-gouv/django-dsfr#90]
D'après un commentaire de @christophehenry sur #83 :

> Ok, je comprends le problème. Ça vient [de la façon de mélanger les `ModelForm` et `DsfrBaseForm`](https://github.com/numerique-gouv/django-dsfr/blob/main/example_app/forms.py#L156). `ModelForm.default_renderer()` prend le pas sur `DsfrBaseForm.default_renderer()`.

> Selon moi, il faudrait déprécier cette méthode en faveur d'un `DsfrModelForm` dans une version majeure, ce qui crérait moins de risque d'erreur avec la résolution des ancêtres.

> Mais si cette solution est écartée, il faudrait au moins remplacer:

```
TEMPLATES = [
    {
        [...]
        "DIRS": [
            os.path.join(BASE_DIR, "dsfr/templates"),
            os.path.join(BASE_DIR, "templates"),
        ],
    },
]
```
> par :

```
INSTALLED_APPS = [
    ...
    "widget_tweaks"
    "dsfr",
    "django.forms",
    <votre_app>
]
```

> dans la documentation pour se rendre conforme avec la documentation Django.

**Comment by christophehenry** [comment]
Erf. Je suis désolé, en fait le problème venait d'un petit bug dans `django.forms.formsets.formset_factory`. Je vais ouvrir une PR pour le corriger.

**Comment by christophehenry** [comment]
J'ai ouvert django/django#17605 pour régler ce problème. J'espère que ça sera accepté sinon il faudra revert #83.

**Comment by christophehenry** [comment]
Il semble que [ce problème ait déjà été soulevé et résolu dans Django 5.0](https://code.djangoproject.com/ticket/34532) (avec [95e4d6b](https://code.djangoproject.com/changeset/95e4d6b81312fdd9f8ebf3385be1c1331168b5cf)) mais le fix n'a pas été reporté sur 4.2, ce qui explique le problème avec les formsets. Je vais essayer de faire passer ça.

**Comment by Ash-Crow** [comment]
Merci !
